version: "3.5"
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=animal_house
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - backend
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=animal_house
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - backend
volumes:
  postgres_data:

networks:
  backend:
     driver: bridge
