# Generated by Django 4.1.2 on 2022-11-09 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PetFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_feed_amount', models.IntegerField()),
                ('pet_feed_price', models.FloatField()),
                ('pet_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pet.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='', max_length=50)),
                ('birthday', models.DateField(default='', validators=[django.core.validators.RegexValidator(regex='^[1-2]\\d{3}-[0-1]\\d-[0-3]\\d$')])),
                ('pet_passport_number', models.IntegerField(blank=True, default='', null=True)),
                ('reason', models.CharField(max_length=150)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pet.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='MedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_sickness', models.CharField(max_length=250)),
                ('measure_date', models.DateField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_high', models.IntegerField(default='')),
                ('pet_weight', models.IntegerField(default='')),
                ('measure_date', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
        ),
    ]
