# Generated by Django 4.1.2 on 2022-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
