# Generated by Django 4.1.2 on 2022-11-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_pet_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medcard',
            old_name='measure_date',
            new_name='MedCard_date',
        ),
    ]
